from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal, Protocol

from app.domain.instruments.models import InstrumentContract
from app.domain.research.models import InstrumentDetailView, MarketOverviewView


@dataclass(frozen=True)
class StorageHealth:
    status: Literal["healthy", "error"]
    database: Literal["postgresql"]
    applied_migrations: int
    expected_migrations: int


class HealthRepository(Protocol):
    def storage_health(self) -> StorageHealth: ...


class AuthRepository(Protocol):
    def get_active_guest_code(
        self,
        code_hash: str,
        now: datetime,
    ) -> dict[str, Any] | None: ...

    def get_active_guest_code_by_id(
        self,
        code_id: int,
        now: datetime,
    ) -> dict[str, Any] | None: ...

    def touch_guest_code(self, code_id: int, now: datetime) -> None: ...

    def record_auth_event(
        self,
        *,
        event_type: str,
        role: str,
        subject_id: str | None,
        guest_code_id: int | None,
        success: bool,
        reason: str | None,
        metadata: dict[str, object],
    ) -> None: ...


class MarketRepository(Protocol):
    def market_overview(self) -> MarketOverviewView: ...

    def search_instruments(
        self,
        query: str,
        asset_class: str | None,
        limit: int,
    ) -> list[InstrumentContract]: ...

    def instrument_detail(self, symbol: str) -> InstrumentDetailView | None: ...

    def daily_bars(self, symbol: str, limit: int) -> list[dict[str, Any]]: ...

    def list_watchlist(self, owner: str) -> list[dict[str, Any]]: ...

    def upsert_watchlist(self, owner: str, symbol: str, note: str) -> dict[str, Any]: ...

    def delete_watchlist(self, owner: str, entry_id: int) -> bool: ...


class PaperRepository(Protocol):
    def list_instances(self) -> list[dict[str, Any]]: ...
    def get_instance(self, instance_id: str) -> dict[str, Any]: ...
    def create_instance(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def start(self, instance_id: str) -> dict[str, Any]: ...
    def pause(self, instance_id: str) -> dict[str, Any]: ...
    def resume(self, instance_id: str) -> dict[str, Any]: ...
    def stop(self, instance_id: str) -> dict[str, Any]: ...
    def advance(self, instance_id: str, max_dates: int) -> dict[str, Any]: ...
    def events(self, instance_id: str) -> list[dict[str, Any]]: ...
    def klines(self, instance_id: str, symbol: str) -> dict[str, Any]: ...
    def continuity_manifest(self) -> dict[str, Any]: ...


class OperationsRepository(Protocol):
    def watch_context(self, scope: str) -> dict[str, Any]: ...
    def health(self, scope: str) -> dict[str, Any]: ...
    def list_alerts(self, status: str | None, limit: int) -> list[dict[str, Any]]: ...
    def acknowledge_alert(self, alert_id: str, actor: str) -> dict[str, Any]: ...
    def get_signal(self, signal_id: str) -> dict[str, Any] | None: ...
    def acknowledge_signal(self, signal_id: str) -> dict[str, Any]: ...
    def list_rules(self, scope: str) -> list[dict[str, Any]]: ...
    def create_rule(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def create_rule_version(self, rule_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def preview_rule(self, rule_id: str) -> dict[str, Any]: ...
    def evaluate_rule(self, rule_id: str) -> dict[str, Any]: ...

class ReviewRepository(Protocol):
    def dates(self, limit: int) -> list[str]: ...
    def list(self, limit: int) -> list[dict[str, Any]]: ...
    def get(self, trade_date: str) -> dict[str, Any]: ...
    def assemble(self, trade_date: str) -> dict[str, Any]: ...
    def save(self, trade_date: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def seal(self, trade_date: str) -> dict[str, Any]: ...
    def resolve(self, object_type: str, object_id: str) -> dict[str, Any]: ...

class DataRepository(Protocol):
    def status(self) -> dict[str, Any]: ...
    def datasets(self) -> list[dict[str, Any]]: ...
    def snapshots(self, limit: int) -> list[dict[str, Any]]: ...
    def providers(self) -> list[dict[str, Any]]: ...
    def schedules(self) -> list[dict[str, Any]]: ...
    def jobs(self, limit: int) -> list[dict[str, Any]]: ...
    def quality(self, limit: int) -> list[dict[str, Any]]: ...
    def imports(self, limit: int) -> list[dict[str, Any]]: ...
    def stage(self, **kwargs: Any) -> dict[str, Any]: ...
    def import_records(self, import_id: str) -> list[dict[str, Any]]: ...
    def create_job(self, job_name: str, source: str, start_date: str | None, end_date: str | None) -> dict[str, Any]: ...
    def update_schedule(self, code: str, payload: dict[str, Any]) -> dict[str, Any]: ...

class AIRepository(Protocol):
    def list_tasks(self, limit: int) -> list[dict[str, Any]]: ...
    def get_task(self, task_id: str) -> dict[str, Any] | None: ...
    def iterations(self, task_id: str) -> list[dict[str, Any]]: ...
    def create_task(self, payload: dict[str, Any], model: str) -> dict[str, Any]: ...
    def fail_task(self, task_id: str, message: str) -> dict[str, Any]: ...
    def stop_task(self, task_id: str) -> dict[str, Any] | None: ...
    def evidence_ready(self, config: dict[str, Any]) -> bool: ...
    def evidence_manifest(self, config: dict[str, Any]) -> dict[str, Any]: ...
    def create_strategy(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def quick_run(self, version_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def record_iteration(self, task_id: str, **kwargs: Any) -> dict[str, Any]: ...
    def complete_task(self, task_id: str, iteration_id: str, success: bool, error: str = "") -> dict[str, Any]: ...
    def promote(self, iteration_id: str) -> dict[str, Any]: ...


class PoolRepository(Protocol):
    def list_pools(self) -> list[dict[str, Any]]: ...
    def get_pool(self, pool_id: str) -> dict[str, Any]: ...
    def create_pool(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def generate(self, pool_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def members(self, pool_id: str, generation_id: str | None = None) -> list[dict[str, Any]]: ...
    def seal_snapshot(self, pool_id: str, generation_id: str | None = None) -> dict[str, Any]: ...
    def list_snapshots(self, pool_id: str | None = None) -> list[dict[str, Any]]: ...
    def get_snapshot(self, snapshot_id: int) -> dict[str, Any]: ...


class FactorRepository(Protocol):
    def list_library(self) -> list[dict[str, Any]]: ...
    def create_factor(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def create_version(self, definition_id: int, payload: dict[str, Any]) -> dict[str, Any]: ...
    def validate_version(self, version_id: int) -> dict[str, Any]: ...
    def compute_factor(self, version_id: int, trade_date: str, dataset_snapshot_id: int, universe_snapshot_id: int) -> dict[str, Any]: ...
    def factor_metrics(self, factor_identifier: str) -> dict[str, Any]: ...
    def factor_values(self, factor_identifier: str, limit: int, offset: int) -> dict[str, Any]: ...
    def list_runs(self, limit: int) -> list[dict[str, Any]]: ...
    def list_correlations(self, trade_date: str | None, limit: int) -> list[dict[str, Any]]: ...
    def list_snapshots(self, limit: int) -> list[dict[str, Any]]: ...
    def get_snapshot(self, snapshot_id: int) -> dict[str, Any] | None: ...
    def snapshot_values(self, snapshot_id: int, factor_code: str | None, limit: int) -> dict[str, Any]: ...


class StrategyRepository(Protocol):
    def list_strategies(self) -> list[dict[str, Any]]: ...
    def get_strategy_version(self, version_id: str) -> dict[str, Any] | None: ...
    def create_strategy(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def create_version(self, parent_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def validate(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def quick_run(self, version_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def update_contract_metadata(self, version_id: str, metadata: dict[str, object]) -> None: ...


class BacktestRepository(Protocol):
    def run(self, payload: dict[str, Any], mode: str) -> dict[str, Any]: ...
    def run_matrix(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def run_walk_forward(self, payload: dict[str, Any]) -> dict[str, Any]: ...


@dataclass(frozen=True)
class Repositories:
    health: HealthRepository
    auth: AuthRepository
    market: MarketRepository
    pools: PoolRepository
    factors: FactorRepository
    strategies: StrategyRepository
    backtests: BacktestRepository
    paper: PaperRepository
    operations: OperationsRepository
    review: ReviewRepository
    data: DataRepository
    ai: AIRepository
