import { expect, test } from '@playwright/test'
import { installFinalFixtures } from './rebuild-final-fixtures'
test('home exposes abnormal windows and an alert-only event stream',async({page})=>{await installFinalFixtures(page);await page.goto('/');await expect(page.getByText('异动边缘',{exact:true}).first()).toBeVisible();await expect(page.getByText('3日 +16.0% / 20% · 80%').first()).toBeVisible();await expect(page.getByText('告警事件流',{exact:true})).toBeVisible();await expect(page.getByText('3日异动边缘',{exact:true})).toBeVisible();await expect(page.getByText(/orders_created=0/)).toBeVisible();await page.getByRole('button',{name:'监控中心'}).click();await expect(page).toHaveURL(/\/monitor/)})
test('home abnormal symbol drilldown goes to the StockPro market page',async({page})=>{await installFinalFixtures(page);await page.goto('/');await page.getByText('贵州茅台（600519.SH）',{exact:true}).first().click();await expect(page).toHaveURL(/\/market/)})
test('home keeps the A-share market overview foundation readable', async ({ page }) => {
  await installFinalFixtures(page)
  await page.goto('/')
  for (const heading of ['市场大盘', 'A 股市场基础层', '指数行情', '市场宽度 · 涨跌分布', '趋势强度', '成交与换手', '排行榜']) {
    await expect(page.getByRole('heading', { name: heading, exact: true }).first()).toBeVisible()
  }
  await expect(page.getByText(/资金费率|杠杆情绪|多空拥挤|USDT|OKX/)).toHaveCount(0)
})

test('home remains readable on a narrow viewport', async ({ page }) => {
  await installFinalFixtures(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '市场大盘' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '指数行情' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
})

test('home phase summary opens the persisted market timeline', async ({ page }) => {
  await installFinalFixtures(page)
  await page.goto('/')
  await page.getByRole('button', { name: '阶段时间轴' }).click()
  await expect(page).toHaveURL(/\/market\?timeline=1/)
  await expect(page.getByRole('heading', { name: '市场情绪时间轴' })).toBeVisible()
  await expect(page.getByText('78', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('#7', { exact: true })).toBeVisible()
})

test('home analysis tabs persist in the URL and render sections', async ({ page }) => {
  await installFinalFixtures(page)
  await page.goto('/')
  const tabs = page.getByRole('navigation', { name: '首页分析板块' })
  await expect(tabs.getByRole('button', { name: '总览' })).toBeVisible()
  await tabs.getByRole('button', { name: '连板梯队' }).click()
  await expect(page).toHaveURL(/\?tab=ladder/)
  await expect(page.getByRole('heading', { name: '连板梯队' })).toBeVisible()
  await expect(page.getByText('蓝盾光电').first()).toBeVisible()
  await tabs.getByRole('button', { name: '概念分析' }).click()
  await expect(page).toHaveURL(/\?tab=concept/)
  await expect(page.getByRole('heading', { name: '概念分析' })).toBeVisible()
  await expect(page.getByText('生物疫苗').first()).toBeVisible()
  await tabs.getByRole('button', { name: '行业分析' }).click()
  await expect(page).toHaveURL(/\?tab=industry/)
  await expect(page.getByRole('heading', { name: '行业分析' })).toBeVisible()
  await expect(page.getByText('领涨行业').first()).toBeVisible()
  await tabs.getByRole('button', { name: '市场环境' }).click()
  await expect(page).toHaveURL(/\?tab=environment/)
  await expect(page.getByRole('heading', { name: '市场环境' })).toBeVisible()
  await expect(page.getByText('领涨行业（等权当日）')).toBeVisible()
  await tabs.getByRole('button', { name: '异动监控' }).click()
  await expect(page).toHaveURL(/\?tab=abnormal/)
  await expect(page.getByRole('heading', { name: '异动监控' })).toBeVisible()
  await tabs.getByRole('button', { name: '个股分析' }).click()
  await expect(page).toHaveURL(/\?tab=stock/)
  await expect(page.getByRole('heading', { name: '个股分析' })).toBeVisible()
  await expect(page.getByText('整数 1500').first()).toBeVisible()
  await page.goto('/?tab=not-a-tab')
  await expect(page.getByRole('heading', { name: 'A 股市场基础层' })).toBeVisible()
})

test('home analysis tabs stay readable on a narrow viewport', async ({ page }) => {
  await installFinalFixtures(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/?tab=ladder')
  await expect(page.getByRole('heading', { name: '连板梯队' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.goto('/?tab=concept')
  await expect(page.getByRole('heading', { name: '概念分析' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
})
