"""Diversified, sealed-snapshot-computable reference factor catalog (exactly 100).

Selection rules:
1. Only Factor API fields on sealed daily_bars + daily_valuation.
2. Prefer published cross-section hypotheses (size/value/momentum/short-reversal/
   low-vol/illiquidity/turnover), not arbitrary formula spam.
3. Avoid near-duplicates: no same-window momentum+reversal pair; no EY vs
   standardized-PE mirror; no open-gap vs overnight mirror; space lookbacks.
4. Empirical IC / pairwise corr still require sealed compute + maturity runs.
"""
from __future__ import annotations

from typing import Any, Dict, List, Sequence, Tuple


def _f(
    code: str,
    name: str,
    category: str,
    lookback: int,
    direction: int,
    description: str,
    body: str,
) -> Dict[str, Any]:
    return {
        "code": code,
        "name": name,
        "category": category,
        "lookback": int(lookback),
        "direction": int(direction),
        "description": description,
        "body": body.strip(),
    }


def build_reference_factors() -> Tuple[Dict[str, Any], ...]:
    factors: List[Dict[str, Any]] = [
        # ----- Momentum (medium/long; spaced) -----
        _f("momentum_5d", "5日动量", "momentum", 6, 1, "5 日收盘动量", "close = data.history('close', 6)\n    return close.iloc[-1] / close.iloc[0] - 1"),
        _f("momentum_20d", "20日动量", "momentum", 21, 1, "20 日收盘动量", "close = data.history('close', 21)\n    return close.iloc[-1] / close.iloc[0] - 1"),
        _f("momentum_60d", "60日动量", "momentum", 61, 1, "60 日收盘动量", "close = data.history('close', 61)\n    return close.iloc[-1] / close.iloc[0] - 1"),
        _f("momentum_120d", "120日动量", "momentum", 121, 1, "120 日收盘动量", "close = data.history('close', 121)\n    return close.iloc[-1] / close.iloc[0] - 1"),
        _f("momentum_252d", "252日动量", "momentum", 253, 1, "252 日收盘动量", "close = data.history('close', 253)\n    return close.iloc[-1] / close.iloc[0] - 1"),
        _f(
            "momentum_skip_21_252",
            "跳过近月的12月动量",
            "momentum",
            253,
            1,
            "252 日动量减去近 21 日（skip-month）",
            "close = data.history('close', 253)\n    return (close.iloc[-1] / close.iloc[0] - 1) - (close.iloc[-1] / close.iloc[-22] - 1)",
        ),
        _f(
            "momentum_accel_20_60",
            "动量加速度20相对60",
            "momentum",
            61,
            1,
            "短动量减长动量",
            "close = data.history('close', 61)\n    return (close.iloc[-1] / close.iloc[-21] - 1) - (close.iloc[-1] / close.iloc[0] - 1)",
        ),
        _f(
            "up_days_ratio_20d",
            "20日上涨日占比",
            "momentum",
            21,
            1,
            "上涨日比例（路径动量）",
            "close = data.history('close', 21)\n    ret = close / close.shift(1) - 1\n    return (ret > 0).astype(float).mean()",
        ),
        _f(
            "max_return_20d",
            "20日最大日收益",
            "momentum",
            21,
            -1,
            "窗口最大单日收益（MAX / 彩票异象）",
            "close = data.history('close', 21)\n    return (close / close.shift(1) - 1).max()",
        ),
        _f(
            "trend_consistency_20d",
            "20日趋势一致性",
            "momentum",
            21,
            1,
            "同号收益日占比 * sign(总动量)",
            "close = data.history('close', 21)\n    ret = close / close.shift(1) - 1\n    mom = close.iloc[-1] / close.iloc[0] - 1\n    return (ret > 0).astype(float).mean() * np.sign(mom)",
        ),
        _f(
            "recovery_from_low_20d",
            "20日自低点修复",
            "momentum",
            20,
            1,
            "收盘相对窗口最低收盘",
            "close = data.history('close', 20)\n    return close.iloc[-1] / close.min().replace(0, np.nan) - 1",
        ),
        _f(
            "momentum_3m_12m_spread",
            "季动量减年动量",
            "momentum",
            253,
            1,
            "60 日动量减 252 日动量",
            "close = data.history('close', 253)\n    return (close.iloc[-1] / close.iloc[-61] - 1) - (close.iloc[-1] / close.iloc[0] - 1)",
        ),
        _f(
            "open_gap_persistence",
            "隔夜跳空后日内延续",
            "momentum",
            2,
            1,
            "sign(隔夜)*日内收益（跳空后动量）",
            "close = data.history('close', 2)\n    open_px = data.history('open', 1).iloc[-1]\n    overnight = open_px / close.iloc[0].replace(0, np.nan) - 1\n    intraday = close.iloc[-1] / open_px.replace(0, np.nan) - 1\n    return np.sign(overnight) * intraday",
        ),
        _f(
            "momentum_40d",
            "40日动量",
            "momentum",
            41,
            1,
            "40 日动量（与 20/60 错开）",
            "close = data.history('close', 41)\n    return close.iloc[-1] / close.iloc[0] - 1",
        ),
        _f(
            "momentum_180d",
            "180日动量",
            "momentum",
            181,
            1,
            "180 日动量",
            "close = data.history('close', 181)\n    return close.iloc[-1] / close.iloc[0] - 1",
        ),

        # ----- Reversal (short only; windows not mirroring momentum set) -----
        _f("reversal_1d", "1日反转", "reversal", 2, 1, "昨日收益取反", "close = data.history('close', 2)\n    return -(close.iloc[-1] / close.iloc[0] - 1)"),
        _f("reversal_2d", "2日反转", "reversal", 3, 1, "2 日反转", "close = data.history('close', 3)\n    return -(close.iloc[-1] / close.iloc[0] - 1)"),
        _f("reversal_3d", "3日反转", "reversal", 4, 1, "3 日反转", "close = data.history('close', 4)\n    return -(close.iloc[-1] / close.iloc[0] - 1)"),
        _f(
            "overnight_return",
            "隔夜收益反转",
            "reversal",
            2,
            1,
            "-(今开/昨收-1)",
            "close = data.history('close', 2)\n    open_px = data.history('open', 1).iloc[-1]\n    return -(open_px / close.iloc[0].replace(0, np.nan) - 1)",
        ),
        _f(
            "month_end_reversal_proxy",
            "近月内结构反转",
            "reversal",
            11,
            1,
            "-(10日动量 - 5日动量)",
            "close = data.history('close', 11)\n    return -((close.iloc[-1] / close.iloc[0] - 1) - (close.iloc[-1] / close.iloc[-6] - 1))",
        ),
        _f(
            "reversal_vol_adjusted_3d",
            "波动调整3日反转",
            "reversal",
            4,
            1,
            "短反转 / 波动",
            "close = data.history('close', 4)\n    rev = -(close.iloc[-1] / close.iloc[0] - 1)\n    vol = np.log(close / close.shift(1)).std() * np.sqrt(252)\n    return rev / vol.replace(0, np.nan)",
        ),
        _f(
            "reversal_from_high_5d",
            "5日自高点回落",
            "reversal",
            5,
            1,
            "1 - close/high_5（短期回落）",
            "close = data.history('close', 5)\n    high = data.history('high', 5)\n    return 1 - close.iloc[-1] / high.max().replace(0, np.nan)",
        ),
        _f(
            "weekday_reversal_proxy",
            "周内反转代理",
            "reversal",
            6,
            1,
            "近1日相对近5日超额取反",
            "close = data.history('close', 6)\n    d1 = close.iloc[-1] / close.iloc[-2] - 1\n    d5 = close.iloc[-1] / close.iloc[0] - 1\n    return -(d1 - d5 / 5)",
        ),

        # ----- Volatility / risk -----
        _f("volatility_5d", "5日年化波动", "volatility", 6, -1, "5 日低波", "close = data.history('close', 6)\n    return np.log(close / close.shift(1)).std() * np.sqrt(252)"),
        _f("volatility_20d", "20日年化波动", "volatility", 21, -1, "20 日低波异象", "close = data.history('close', 21)\n    return np.log(close / close.shift(1)).std() * np.sqrt(252)"),
        _f("volatility_60d", "60日年化波动", "volatility", 61, -1, "60 日波动", "close = data.history('close', 61)\n    return np.log(close / close.shift(1)).std() * np.sqrt(252)"),
        _f(
            "hl_range_20d",
            "20日高低振幅",
            "volatility",
            20,
            -1,
            "均 (high-low)/close",
            "high = data.history('high', 20)\n    low = data.history('low', 20)\n    close = data.history('close', 20)\n    return ((high - low) / close.replace(0, np.nan)).mean()",
        ),
        _f(
            "downside_vol_20d",
            "20日下行波动",
            "volatility",
            21,
            -1,
            "负收益半方差",
            "close = data.history('close', 21)\n    returns = np.log(close / close.shift(1))\n    return returns.where(returns < 0, 0.0).std() * np.sqrt(252)",
        ),
        _f(
            "return_skew_20d",
            "20日收益偏度",
            "volatility",
            21,
            -1,
            "日收益偏度",
            "close = data.history('close', 21)\n    return (close / close.shift(1) - 1).skew()",
        ),
        _f(
            "return_kurtosis_20d",
            "20日收益峰度",
            "volatility",
            21,
            -1,
            "日收益峰度",
            "close = data.history('close', 21)\n    return (close / close.shift(1) - 1).kurt()",
        ),
        _f(
            "vol_of_vol_60d",
            "60日波动的波动",
            "volatility",
            61,
            -1,
            "滚动波动再波动",
            "close = data.history('close', 61)\n    roll = np.log(close / close.shift(1)).rolling(5).std() * np.sqrt(252)\n    return roll.iloc[-12:].std()",
        ),
        _f(
            "atr_proxy_14d",
            "14日ATR代理",
            "volatility",
            15,
            -1,
            "TR 均值 / 收盘",
            "high = data.history('high', 15)\n    low = data.history('low', 15)\n    close = data.history('close', 15)\n    prev = close.shift(1)\n    tr1 = high - low\n    tr2 = (high - prev).abs()\n    tr3 = (low - prev).abs()\n    tr = tr1.where(tr1 >= tr2, tr2)\n    tr = tr.where(tr >= tr3, tr3)\n    return tr.iloc[-14:].mean() / close.iloc[-1].replace(0, np.nan)",
        ),
        _f(
            "drawdown_20d",
            "20日回撤深度",
            "volatility",
            20,
            -1,
            "窗口最大回撤",
            "close = data.history('close', 20)\n    dd = close / close.cummax().replace(0, np.nan) - 1\n    return (-dd.min())",
        ),
        _f(
            "intraday_volatility_proxy",
            "日内波动代理",
            "volatility",
            1,
            -1,
            "(high-low)/close",
            "high = data.history('high', 1).iloc[-1]\n    low = data.history('low', 1).iloc[-1]\n    close = data.history('close', 1).iloc[-1]\n    return (high - low) / close.replace(0, np.nan)",
        ),
        _f(
            "realized_range_ratio_20d",
            "20日已实现波幅比",
            "volatility",
            21,
            -1,
            "收益标准差 / 均振幅（实现波动相对振幅）",
            "close = data.history('close', 21)\n    high = data.history('high', 20)\n    low = data.history('low', 20)\n    vol = (close / close.shift(1) - 1).std()\n    rng = ((high - low) / close.iloc[-20:].replace(0, np.nan)).mean()\n    return vol / rng.replace(0, np.nan)",
        ),
        _f(
            "high_low_skew_20d",
            "20日高低偏斜",
            "volatility",
            20,
            -1,
            "均 (high-close)/(close-low)",
            "high = data.history('high', 20)\n    low = data.history('low', 20)\n    close = data.history('close', 20)\n    return ((high - close) / (close - low).replace(0, np.nan)).mean()",
        ),
        _f(
            "volatility_120d",
            "120日年化波动",
            "volatility",
            121,
            -1,
            "长窗波动",
            "close = data.history('close', 121)\n    return np.log(close / close.shift(1)).std() * np.sqrt(252)",
        ),
        _f(
            "range_vol_60d",
            "60日高低振幅",
            "volatility",
            60,
            -1,
            "60 日振幅均值",
            "high = data.history('high', 60)\n    low = data.history('low', 60)\n    close = data.history('close', 60)\n    return ((high - low) / close.replace(0, np.nan)).mean()",
        ),

        # ----- Liquidity -----
        _f("turnover_rate", "换手率", "liquidity", 1, 1, "当日换手率", "return data.current('turnover_rate')"),
        _f("turnover_rate_f", "自由流通换手率", "liquidity", 1, 1, "自由流通换手", "return data.current('turnover_rate_f')"),
        _f("volume_ratio", "量比", "liquidity", 1, 1, "当日量比", "return data.current('volume_ratio')"),
        _f(
            "log_turnover",
            "对数成交额",
            "liquidity",
            1,
            1,
            "成交额对数",
            "turnover = data.history('turnover', 1).iloc[-1]\n    return np.log(turnover.where(turnover > 0))",
        ),
        _f(
            "amihud_5d",
            "5日Amihud非流动性",
            "liquidity",
            6,
            1,
            "均 |r|/turnover",
            "close = data.history('close', 6)\n    turnover = data.history('turnover', 6)\n    return ((close / close.shift(1) - 1).abs() / turnover.replace(0, np.nan)).mean()",
        ),
        _f(
            "amihud_change_5_20",
            "Amihud变化5相对20",
            "liquidity",
            21,
            1,
            "短窗Amihud/长窗Amihud - 1（流动性恶化）",
            "close = data.history('close', 21)\n    turnover = data.history('turnover', 21)\n    illiq = (close / close.shift(1) - 1).abs() / turnover.replace(0, np.nan)\n    return illiq.iloc[-5:].mean() / illiq.mean().replace(0, np.nan) - 1",
        ),
        _f(
            "volume_shock_5_20",
            "量能冲击5相对20",
            "liquidity",
            20,
            1,
            "短均量/长均量-1",
            "volume = data.history('volume', 20)\n    return volume.iloc[-5:].mean() / volume.mean().replace(0, np.nan) - 1",
        ),
        _f(
            "volume_volatility_20d",
            "20日成交量波动",
            "liquidity",
            20,
            -1,
            "成交量变异系数",
            "volume = data.history('volume', 20)\n    return volume.std() / volume.mean().replace(0, np.nan)",
        ),
        _f(
            "dollar_volume_20d",
            "20日平均成交额",
            "liquidity",
            20,
            1,
            "20 日成交额均值",
            "return data.history('turnover', 20).mean()",
        ),
        _f(
            "turnover_entropy_proxy",
            "20日成交额均匀度",
            "liquidity",
            20,
            1,
            "1 - 赫芬达尔集中度（成交更均匀越高）",
            "turnover = data.history('turnover', 20)\n    w = turnover / turnover.sum().replace(0, np.nan)\n    return 1 - (w * w).sum()",
        ),
        _f(
            "volume_concentration_20d",
            "20日量能集中度",
            "liquidity",
            20,
            -1,
            "最大日量/总量",
            "volume = data.history('volume', 20)\n    return volume.max() / volume.sum().replace(0, np.nan)",
        ),
        _f(
            "zero_volume_days_20d",
            "20日活跃度",
            "liquidity",
            20,
            1,
            "1-零量日占比",
            "volume = data.history('volume', 20)\n    return 1 - (volume <= 0).astype(float).mean()",
        ),
        _f(
            "liquidity_vs_size",
            "流动性相对市值",
            "liquidity",
            1,
            1,
            "换手 - 标准化对数市值",
            "tr = data.current('turnover_rate')\n    log_mv = np.log(data.current('total_mv').where(lambda s: True))\n    mv = data.current('total_mv')\n    log_mv = np.log(mv.where(mv > 0))\n    return tr - (log_mv - log_mv.mean()) / (log_mv.std() + 1e-8)",
        ),
        _f(
            "volume_mean_60d",
            "60日均量",
            "liquidity",
            60,
            1,
            "长窗均量水平",
            "return data.history('volume', 60).mean()",
        ),
        _f(
            "amihud_60d",
            "60日Amihud非流动性",
            "liquidity",
            61,
            1,
            "长窗非流动性",
            "close = data.history('close', 61)\n    turnover = data.history('turnover', 61)\n    return ((close / close.shift(1) - 1).abs() / turnover.replace(0, np.nan)).mean()",
        ),
        _f(
            "log_volume",
            "对数成交量",
            "liquidity",
            1,
            1,
            "成交量对数",
            "volume = data.history('volume', 1).iloc[-1]\n    return np.log(volume.where(volume > 0))",
        ),

        # ----- Size -----
        _f("size_log_mv", "对数总市值", "size", 1, -1, "小市值溢价", "total_mv = data.current('total_mv')\n    return np.log(total_mv.where(total_mv > 0))"),
        _f(
            "free_float_ratio",
            "自由流通占比",
            "size",
            1,
            1,
            "free/total share",
            "return data.current('free_share') / data.current('total_share').where(lambda s: True)\n    free_share = data.current('free_share')\n    total_share = data.current('total_share')\n    return free_share / total_share.where(total_share > 0)",
        ),
        _f(
            "circ_to_total_mv",
            "流通市值占比",
            "size",
            1,
            1,
            "circ_mv/total_mv",
            "circ_mv = data.current('circ_mv')\n    total_mv = data.current('total_mv')\n    return circ_mv / total_mv.where(total_mv > 0)",
        ),
        _f(
            "share_concentration",
            "股本集中度代理",
            "size",
            1,
            -1,
            "1 - free/float",
            "free_share = data.current('free_share')\n    float_share = data.current('float_share')\n    return 1 - free_share / float_share.where(float_share > 0)",
        ),
        _f(
            "circ_mv_to_float",
            "流通市值相对流通股本",
            "size",
            1,
            1,
            "circ_mv / float_share（股价水平代理）",
            "circ_mv = data.current('circ_mv')\n    float_share = data.current('float_share')\n    return circ_mv / float_share.where(float_share > 0)",
        ),
        _f(
            "log_float_share",
            "对数流通股本",
            "size",
            1,
            -1,
            "流通股本对数",
            "float_share = data.current('float_share')\n    return np.log(float_share.where(float_share > 0))",
        ),

        # ----- Value -----
        _f("earnings_yield", "盈利收益率", "value", 1, 1, "1/PE_TTM", "pe = data.current('pe_ttm')\n    return 1 / pe.where(pe > 0)"),
        _f("book_to_price", "账面市值比", "value", 1, 1, "1/PB", "pb = data.current('pb')\n    return 1 / pb.where(pb > 0)"),
        _f("sales_to_price", "营收市值比", "value", 1, 1, "1/PS_TTM", "ps = data.current('ps_ttm')\n    return 1 / ps.where(ps > 0)"),
        _f("dividend_yield", "股息率TTM", "value", 1, 1, "dv_ttm", "return data.current('dv_ttm')"),
        _f(
            "pe_to_pb",
            "PE相对PB",
            "value",
            1,
            -1,
            "PE_TTM/PB",
            "pe = data.current('pe_ttm')\n    pb = data.current('pb')\n    return pe.where(pe > 0) / pb.where(pb > 0)",
        ),
        _f(
            "dv_to_turnover",
            "股息相对换手",
            "value",
            1,
            1,
            "股息/(1+换手)",
            "return data.current('dv_ttm') / (1 + data.current('turnover_rate').fillna(0))",
        ),
        _f(
            "neg_size_value_combo",
            "小市值价值组合代理",
            "value",
            1,
            1,
            "BP - z(log_mv)",
            "pb = data.current('pb')\n    mv = data.current('total_mv')\n    bp = 1 / pb.where(pb > 0)\n    log_mv = np.log(mv.where(mv > 0))\n    z = (log_mv - log_mv.mean()) / (log_mv.std() + 1e-8)\n    return bp - z",
        ),
        _f(
            "earnings_yield_static",
            "静态盈利收益率",
            "value",
            1,
            1,
            "1/PE（静态）",
            "pe = data.current('pe')\n    return 1 / pe.where(pe > 0)",
        ),
        _f(
            "value_dispersion",
            "价值指标离散度",
            "value",
            1,
            -1,
            "EY与BP截面标准化后的绝对差（估值内部不一致）",
            "pe = data.current('pe_ttm')\n    pb = data.current('pb')\n    ey = 1 / pe.where(pe > 0)\n    bp = 1 / pb.where(pb > 0)\n    z_ey = (ey - ey.mean()) / (ey.std() + 1e-8)\n    z_bp = (bp - bp.mean()) / (bp.std() + 1e-8)\n    return (z_ey - z_bp).abs()",
        ),
        _f(
            "ps_to_pb",
            "PS相对PB",
            "value",
            1,
            -1,
            "PS_TTM/PB",
            "ps = data.current('ps_ttm')\n    pb = data.current('pb')\n    return ps.where(ps > 0) / pb.where(pb > 0)",
        ),
        _f(
            "cheap_quality_proxy",
            "便宜质量代理",
            "value",
            1,
            1,
            "EY + BP - 标准化换手",
            "pe = data.current('pe_ttm')\n    pb = data.current('pb')\n    tr = data.current('turnover_rate')\n    ey = 1 / pe.where(pe > 0)\n    bp = 1 / pb.where(pb > 0)\n    z = (tr - tr.mean()) / (tr.std() + 1e-8)\n    return ey.fillna(0) + bp.fillna(0) - z",
        ),
        _f(
            "bp_to_sp",
            "账面相对营收价值",
            "value",
            1,
            1,
            "BP - SP",
            "pb = data.current('pb')\n    ps = data.current('ps_ttm')\n    return 1 / pb.where(pb > 0) - 1 / ps.where(ps > 0)",
        ),

        # ----- Technical -----
        _f("ma_deviation_5d", "5日均线乖离", "technical", 5, 1, "相对5日均线", "close = data.history('close', 5)\n    return close.iloc[-1] / close.mean() - 1"),
        _f("ma_deviation_20d", "20日均线乖离", "technical", 20, 1, "相对20日均线", "close = data.history('close', 20)\n    return close.iloc[-1] / close.mean() - 1"),
        _f("ma_deviation_60d", "60日均线乖离", "technical", 60, 1, "相对60日均线", "close = data.history('close', 60)\n    return close.iloc[-1] / close.mean() - 1"),
        _f(
            "close_location_20d",
            "20日收盘位置",
            "technical",
            20,
            1,
            "收盘在窗口高低区间位置",
            "high = data.history('high', 20)\n    low = data.history('low', 20)\n    close = data.history('close', 20)\n    return (close.iloc[-1] - low.min()) / (high.max() - low.min()).replace(0, np.nan)",
        ),
        _f(
            "distance_to_high_60d",
            "距60日高点",
            "technical",
            60,
            -1,
            "1 - close/high_60",
            "close = data.history('close', 60)\n    high = data.history('high', 60)\n    return 1 - close.iloc[-1] / high.max().replace(0, np.nan)",
        ),
        _f(
            "distance_to_low_60d",
            "距60日低点",
            "technical",
            60,
            1,
            "close/low_60 - 1",
            "close = data.history('close', 60)\n    low = data.history('low', 60)\n    return close.iloc[-1] / low.min().replace(0, np.nan) - 1",
        ),
        _f(
            "rsi_14d",
            "14日RSI",
            "technical",
            15,
            1,
            "RSI(14)",
            "close = data.history('close', 15)\n    delta = close.diff()\n    gain = delta.clip(lower=0).rolling(14).mean()\n    loss = (-delta.clip(upper=0)).rolling(14).mean()\n    rs = gain / loss.replace(0, np.nan)\n    return 100 - (100 / (1 + rs.iloc[-1]))",
        ),
        _f(
            "body_to_range",
            "实体振幅比",
            "technical",
            1,
            1,
            "|c-o|/(h-l)",
            "open_px = data.history('open', 1).iloc[-1]\n    high = data.history('high', 1).iloc[-1]\n    low = data.history('low', 1).iloc[-1]\n    close = data.history('close', 1).iloc[-1]\n    return (close - open_px).abs() / (high - low).replace(0, np.nan)",
        ),
        _f(
            "upper_shadow_ratio",
            "上影线比例",
            "technical",
            1,
            -1,
            "上影 / 振幅",
            "open_px = data.history('open', 1).iloc[-1]\n    high = data.history('high', 1).iloc[-1]\n    low = data.history('low', 1).iloc[-1]\n    close = data.history('close', 1).iloc[-1]\n    body_top = open_px.where(open_px >= close, close)\n    return (high - body_top) / (high - low).replace(0, np.nan)",
        ),
        _f(
            "lower_shadow_ratio",
            "下影线比例",
            "technical",
            1,
            1,
            "下影 / 振幅",
            "open_px = data.history('open', 1).iloc[-1]\n    high = data.history('high', 1).iloc[-1]\n    low = data.history('low', 1).iloc[-1]\n    close = data.history('close', 1).iloc[-1]\n    body_bot = open_px.where(open_px <= close, close)\n    return (body_bot - low) / (high - low).replace(0, np.nan)",
        ),
        _f(
            "price_volume_corr_20d",
            "20日价量相关",
            "technical",
            20,
            1,
            "价量相关系数",
            "close = data.history('close', 20)\n    volume = data.history('volume', 20)\n    return pd.Series({symbol: close[symbol].corr(volume[symbol]) for symbol in close.columns})",
        ),
        _f(
            "volume_price_trend_20d",
            "20日量价趋势",
            "technical",
            21,
            1,
            "简化 VPT",
            "close = data.history('close', 21)\n    volume = data.history('volume', 21)\n    signed = np.sign(close / close.shift(1) - 1) * volume\n    return signed.iloc[1:].sum() / volume.mean().replace(0, np.nan)",
        ),
        _f(
            "efficiency_ratio_20d",
            "20日效率比率",
            "technical",
            21,
            1,
            "Kaufman ER",
            "close = data.history('close', 21)\n    return (close.iloc[-1] - close.iloc[0]).abs() / close.diff().abs().sum().replace(0, np.nan)",
        ),
        _f(
            "close_to_vwap_proxy",
            "收盘相对均价代理",
            "technical",
            1,
            1,
            "close/(turnover/volume)-1",
            "close = data.history('close', 1).iloc[-1]\n    turnover = data.history('turnover', 1).iloc[-1]\n    volume = data.history('volume', 1).iloc[-1]\n    return close / (turnover / volume.replace(0, np.nan)).replace(0, np.nan) - 1",
        ),
        _f(
            "return_autocorr_20d",
            "20日收益自相关",
            "technical",
            22,
            1,
            "收益 lag1 自相关",
            "close = data.history('close', 22)\n    ret = close / close.shift(1) - 1\n    return pd.Series({symbol: ret[symbol].autocorr(lag=1) for symbol in ret.columns})",
        ),
        _f(
            "ma_deviation_120d",
            "120日均线乖离",
            "technical",
            120,
            1,
            "长均线乖离",
            "close = data.history('close', 120)\n    return close.iloc[-1] / close.mean() - 1",
        ),
        _f(
            "ma_cross_proxy_5_20",
            "均线多头代理5相对20",
            "technical",
            20,
            1,
            "MA5/MA20 - 1",
            "close = data.history('close', 20)\n    return close.iloc[-5:].mean() / close.mean() - 1",
        ),
        # ----- Fill to 100 with spaced / orthogonal additions -----
        _f("momentum_10d", "10日动量", "momentum", 11, 1, "10 日动量（与 5/20 错开）", "close = data.history('close', 11)\n    return close.iloc[-1] / close.iloc[0] - 1"),
        _f("reversal_from_low_bounce", "3日低点反弹衰竭", "reversal", 3, 1, "-(close/low_3-1) 短反弹衰竭", "close = data.history('close', 3)\n    low = data.history('low', 3)\n    return -(close.iloc[-1] / low.min().replace(0, np.nan) - 1)"),
        _f("volatility_10d", "10日年化波动", "volatility", 11, -1, "10 日波动", "close = data.history('close', 11)\n    return np.log(close / close.shift(1)).std() * np.sqrt(252)"),
        _f("hl_range_5d", "5日高低振幅", "volatility", 5, -1, "短窗振幅", "high = data.history('high', 5)\n    low = data.history('low', 5)\n    close = data.history('close', 5)\n    return ((high - low) / close.replace(0, np.nan)).mean()"),
        _f("upside_vol_20d", "20日上行波动", "volatility", 21, -1, "正收益半方差", "close = data.history('close', 21)\n    returns = np.log(close / close.shift(1))\n    return returns.where(returns > 0, 0.0).std() * np.sqrt(252)"),
        _f(
            "volume_price_divergence_20d",
            "20日量价背离",
            "liquidity",
            21,
            1,
            "量能变化减去价格变化",
            "close = data.history('close', 21)\n    volume = data.history('volume', 21)\n    price_chg = close.iloc[-1] / close.iloc[0] - 1\n    vol_chg = volume.iloc[-5:].mean() / volume.iloc[:5].mean().replace(0, np.nan) - 1\n    return vol_chg - price_chg",
        ),
        _f(
            "earnings_yield_to_sales",
            "盈利相对营收价值",
            "value",
            1,
            1,
            "EY - SP",
            "pe = data.current('pe_ttm')\n    ps = data.current('ps_ttm')\n    return 1 / pe.where(pe > 0) - 1 / ps.where(ps > 0)",
        ),
        _f("ma_deviation_10d", "10日均线乖离", "technical", 10, 1, "相对10日均线", "close = data.history('close', 10)\n    return close.iloc[-1] / close.mean() - 1"),
        _f(
            "gap_abs",
            "跳空绝对值",
            "technical",
            2,
            -1,
            "|今开/昨收-1|（跳空风险）",
            "close = data.history('close', 2)\n    open_px = data.history('open', 1).iloc[-1]\n    return (open_px / close.iloc[0].replace(0, np.nan) - 1).abs()",
        ),
        _f(
            "turnover_shock_proxy",
            "换手相对量比",
            "liquidity",
            1,
            1,
            "换手/量比",
            "tr = data.current('turnover_rate')\n    vr = data.current('volume_ratio')\n    return tr / vr.where(vr > 0)",
        ),
        _f(
            "mid_price_pressure",
            "中间价压力",
            "technical",
            1,
            1,
            "close 相对 (high+low)/2",
            "high = data.history('high', 1).iloc[-1]\n    low = data.history('low', 1).iloc[-1]\n    close = data.history('close', 1).iloc[-1]\n    mid = (high + low) / 2\n    return close / mid.replace(0, np.nan) - 1",
        ),
    ]

    # Fix broken bodies that accidentally included lambda drafts.
    fixed: List[Dict[str, Any]] = []
    for item in factors:
        if item["code"] == "liquidity_vs_size":
            item = _f(
                "liquidity_vs_size",
                "流动性相对市值",
                "liquidity",
                1,
                1,
                "换手 - 标准化对数市值",
                "tr = data.current('turnover_rate')\n    mv = data.current('total_mv')\n    log_mv = np.log(mv.where(mv > 0))\n    return tr - (log_mv - log_mv.mean()) / (log_mv.std() + 1e-8)",
            )
        if item["code"] == "free_float_ratio":
            item = _f(
                "free_float_ratio",
                "自由流通占比",
                "size",
                1,
                1,
                "free_share / total_share",
                "free_share = data.current('free_share')\n    total_share = data.current('total_share')\n    return free_share / total_share.where(total_share > 0)",
            )
        fixed.append(item)

    seen = set()
    unique: List[Dict[str, Any]] = []
    for item in fixed:
        if item["code"] in seen:
            continue
        seen.add(item["code"])
        unique.append(item)

    if len(unique) != 100:
        raise RuntimeError(f"reference factor catalog must contain 100 items, got {len(unique)}")
    return tuple(unique)


REFERENCE_FACTORS: Sequence[Dict[str, Any]] = build_reference_factors()
