import { useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, BellRing, Clock3, Database, HeartPulse, RefreshCw, ServerCog, ShieldAlert } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { monitorCurrentApi } from '../api/client'
import type { MonitorSummary } from '../types/operations'

const dt = (value: unknown) => value ? String(value).replace('T',' ').slice(0,19) : '—'
const healthTone = (value: string) => value === 'healthy' || value === 'fresh' ? 'text-emerald-300' : value === 'critical' || value === 'failed' ? 'text-red-300' : value === 'stopped' || value === 'draft' ? 'text-gray-500' : 'text-amber-200'

export default function Monitor() {
  const [view,setView]=useState<MonitorSummary|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  const load=async()=>{setLoading(true);try{setView(await monitorCurrentApi.summary('audit'));setError('')}catch(requestError:any){setError(requestError?.response?.data?.detail||requestError?.message||'监控证据读取失败')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  const running=useMemo(()=>view?.strategy_health.filter((item)=>item.lifecycle_status==='running').length??null,[view]); const unhealthy=useMemo(()=>view?.strategy_health.filter((item)=>['stale','missing','failed'].includes(item.health_state)).length??null,[view])
  const metrics:Array<[string,string|number,LucideIcon]>=[['整体状态',view?.overall_status||'—',HeartPulse],['运行实例',running??'—',Activity],['健康异常',unhealthy??'—',AlertTriangle],['活动告警',view?.active_alerts.length??'—',ShieldAlert]]
  return <div className="h-full overflow-y-auto bg-crypto-bg px-4 py-4 text-gray-100 sm:px-6"><header className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg border border-blue-500/25 bg-blue-500/10"><HeartPulse className="h-5 w-5 text-blue-300" /></div><div><div className="text-[10px] font-semibold uppercase tracking-[.18em] text-blue-300/80">Runtime Health</div><h1 className="text-xl font-bold">监控</h1></div></div><button type="button" onClick={()=>void load()} className="inline-flex items-center gap-1.5 rounded border border-crypto-border px-3 py-2 text-xs text-gray-400"><RefreshCw className={`h-3.5 w-3.5 ${loading?'animate-spin':''}`} />刷新</button></header>
    {error&&<div className="mb-4 rounded border border-red-500/25 bg-red-500/10 p-3 text-xs text-red-200">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon])=><div key={label} className="rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="flex items-center justify-between text-[11px] text-gray-500"><span>{label}</span><Icon className="h-4 w-4 text-blue-400/70" /></div><div className={`mt-2 truncate font-mono text-2xl font-semibold ${label==='整体状态'?healthTone(String(value)):'text-gray-100'}`}>{value}</div></div>)}</div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.75fr_1.25fr]"><section className="rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="mb-3 flex items-center gap-2"><ServerCog className="h-4 w-4 text-blue-300" /><h2 className="text-sm font-semibold">服务健康</h2></div><div className="space-y-2">{(view?.services||[]).map((item)=><div key={String(item.service_code)} className="rounded border border-crypto-border bg-crypto-bg/50 p-3"><div className="flex justify-between gap-2"><span className="text-xs text-gray-200">{item.service_code}</span><span className={`text-[10px] ${healthTone(item.status)}`}>{item.status} · {item.freshness}</span></div><div className="mt-1 text-[10px] text-gray-600">证据 {dt(item.observed_at)} · 延迟 {item.latency_ms??'—'}ms</div></div>)}{!view?.services?.length&&<div className="text-xs text-gray-500">服务健康证据为空</div>}</div></section>
      <section className="rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-blue-300" /><h2 className="text-sm font-semibold">策略健康</h2></div><span className="text-[10px] text-gray-600">生命周期与健康分离</span></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs"><thead className="text-[10px] text-gray-600"><tr>{['实例','生命周期','健康','心跳年龄','最近周期','权益日期','账本差异'].map((item)=><th key={item} className="border-b border-crypto-border px-3 py-2 font-medium">{item}</th>)}</tr></thead><tbody>{(view?.strategy_health||[]).map((item)=><tr data-paper-instance-id={item.id} key={item.id} className="border-b border-crypto-border/60"><td className="px-3 py-2.5"><div className="max-w-52 truncate">{item.name}</div><div className="font-mono text-[10px] text-gray-700">{item.id}</div></td><td className="px-3 py-2.5 text-gray-300">{item.lifecycle_status}</td><td className={`px-3 py-2.5 ${healthTone(item.health_state)}`}>{item.health_state}</td><td className="px-3 py-2.5 font-mono text-gray-500">{item.heartbeat_age_seconds??'—'}</td><td className="px-3 py-2.5 text-gray-500">{dt(item.latest_cycle_finished_at)}</td><td className="px-3 py-2.5 text-gray-500">{String(item.latest_equity_trade_date||'—').slice(0,10)}</td><td className="px-3 py-2.5 font-mono text-gray-400">{item.latest_cycle_ledger_difference??'—'}</td></tr>)}</tbody></table></div></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><section className="rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="mb-3 flex items-center gap-2"><Database className="h-4 w-4 text-blue-300" /><h2 className="text-sm font-semibold">数据状态</h2></div>{[['Dataset',view?.data?.dataset],['市场证据',view?.data?.market]].map(([label,item])=><div key={String(label)} className="mb-2 rounded border border-crypto-border bg-crypto-bg/50 p-3"><div className="flex justify-between text-xs"><span>{label as string}</span><span className={healthTone(String((item as any)?.status||'missing'))}>{(item as any)?.status||'missing'}</span></div><div className="mt-1 font-mono text-[10px] text-gray-600">{(item as any)?.knowledge_cutoff_at||(item as any)?.available_at||'—'}</div></div>)}</section><section className="rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="mb-3 flex items-center gap-2"><ShieldAlert className="h-4 w-4 text-blue-300" /><h2 className="text-sm font-semibold">风险告警</h2></div><div className="max-h-64 space-y-2 overflow-y-auto">{(view?.active_alerts||[]).slice(0,12).map((item)=><div key={item.id} className="rounded border border-crypto-border bg-crypto-bg/50 p-3"><div className="flex justify-between gap-2 text-xs"><span>{item.title}</span><span className={healthTone(item.severity)}>{item.severity}</span></div><div className="mt-1 truncate text-[10px] text-gray-600">{item.message}</div></div>)}</div></section><section className="rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="mb-3 flex items-center gap-2"><BellRing className="h-4 w-4 text-blue-300" /><h2 className="text-sm font-semibold">通知</h2></div><div className="space-y-2">{(view?.notifications||[]).map((item)=><div key={String(item.status)} className="flex justify-between rounded border border-crypto-border bg-crypto-bg/50 p-3 text-xs"><span>{item.status}</span><span className="font-mono text-gray-400">{item.count}</span></div>)}</div></section></div>
    <div className="mt-4 flex items-center gap-2 text-[10px] text-gray-700"><Clock3 className="h-3 w-3" />证据更新时间 {dt(view?.source_updated_at)}；响应生成时间不覆盖证据时间。</div>
  </div>
}
