import { useEffect, useMemo, useState } from 'react'
import { BarChart3, CalendarDays, CheckCircle2, Clock3, FileCheck2, RefreshCw, Save, ShieldCheck, Sparkles } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { reviewCurrentApi } from '../api/client'
import { useAuth } from '../auth/AuthProvider'
import type { DailyReviewView } from '../types/operations'

const categories=['all','market','pool','strategy','risk','order','trade','performance'] as const
const labels:Record<string,string>={all:'全部',market:'市场',pool:'股票池',strategy:'策略',risk:'风险',order:'订单',trade:'成交',performance:'表现'}
const dt=(value:unknown)=>value?String(value).replace('T',' ').slice(0,19):'—'

export default function ReviewDashboard(){
  const {role}=useAuth();const [dates,setDates]=useState<string[]>([]);const [tradeDate,setTradeDate]=useState('');const [view,setView]=useState<DailyReviewView|null>(null);const [category,setCategory]=useState('all');const [summary,setSummary]=useState('');const [plan,setPlan]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const loadDate=async(date:string)=>{setLoading(true);try{const next=await reviewCurrentApi.get(date);setView(next);setSummary(next.review?.summary||'');setPlan(next.review?.next_day_plan||'');setError('')}catch(requestError:any){setError(requestError?.response?.data?.detail||requestError?.message||'复盘读取失败')}finally{setLoading(false)}}
  useEffect(()=>{void(async()=>{try{const [dateResult,listResult]=await Promise.all([reviewCurrentApi.dates(),reviewCurrentApi.list()]);setDates(dateResult.items);const target=String(listResult.items[0]?.trade_date||dateResult.items[0]||'').slice(0,10);setTradeDate(target);if(target)await loadDate(target);else setLoading(false)}catch(error:any){setError(error?.message||'复盘日期读取失败');setLoading(false)}})()},[])
  const selectDate=(date:string)=>{setTradeDate(date);void loadDate(date)}
  const assemble=async()=>{if(!tradeDate||!window.confirm(`确认显式组装 ${tradeDate} 复盘？将写入审计快照。`))return;setSaving(true);try{const next=await reviewCurrentApi.assemble(tradeDate);setView(next)}finally{setSaving(false)}}
  const save=async()=>{setSaving(true);try{setView(await reviewCurrentApi.save(tradeDate,{summary,next_day_plan:plan}))}finally{setSaving(false)}}
  const seal=async()=>{if(!window.confirm('确认封存？封存后的复盘和证据不可修改。'))return;setSaving(true);try{setView(await reviewCurrentApi.seal(tradeDate))}finally{setSaving(false)}}
  const visible=useMemo(()=>view?.items.filter(item=>category==='all'||item.category===category)||[],[category,view])
  const metrics:Array<[string,string|number,LucideIcon]>=[['证据对象',view?.items.length??'—',FileCheck2],['量化指标',view?.metrics.length??'—',BarChart3],['风险事件',view?.counts?.risk??0,ShieldCheck],['状态',view?.status??'—',CheckCircle2]]
  return <div className="h-full overflow-y-auto bg-crypto-bg px-4 py-4 text-gray-100 sm:px-6"><header className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg border border-blue-500/25 bg-blue-500/10"><CalendarDays className="h-5 w-5 text-blue-300" /></div><div><div className="text-[10px] font-semibold uppercase tracking-[.18em] text-blue-300/80">Trading Day Review</div><h1 className="text-xl font-bold">交易日复盘</h1></div></div><div className="flex gap-2"><select aria-label="复盘交易日" value={tradeDate} onChange={event=>selectDate(event.target.value)} className="rounded border border-crypto-border bg-crypto-card px-3 py-2 text-xs">{dates.map(date=><option key={date} value={date}>{date}</option>)}</select><button type="button" onClick={()=>tradeDate&&void loadDate(tradeDate)} className="rounded border border-crypto-border p-2 text-gray-400" aria-label="刷新复盘"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`} /></button></div></header>
    {error&&<div className="mb-4 rounded border border-red-500/25 bg-red-500/10 p-3 text-xs text-red-200">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon])=><div key={label} className="rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="flex items-center justify-between text-[11px] text-gray-500"><span>{label}</span><Icon className="h-4 w-4 text-blue-400/70" /></div><div className="mt-2 font-mono text-2xl font-semibold">{value}</div></div>)}</div>
    {view?.status==='missing'&&<section className="mt-4 rounded-xl border border-dashed border-crypto-border bg-crypto-card p-8 text-center"><Sparkles className="mx-auto h-7 w-7 text-gray-600" /><h2 className="mt-3 text-sm font-semibold">该交易日尚未组装复盘</h2><p className="mt-2 text-xs text-gray-500">页面读取不会自动 assemble、save 或 seal。</p>{role==='admin'&&<button type="button" disabled={saving} onClick={()=>void assemble()} className="mt-4 rounded bg-blue-600 px-4 py-2 text-xs font-semibold">显式组装</button>}</section>}
    {view?.review&&<><div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">交易日 Snapshot</h2><span className="font-mono text-[10px] text-gray-600">{view.source_manifest_hash||'—'}</span></div><div className="grid gap-2 sm:grid-cols-2">{view.metrics.slice(0,12).map(item=><div key={String(item.id||item.metric_code)} className="rounded border border-crypto-border bg-crypto-bg/50 p-3"><div className="truncate text-[10px] text-gray-600">{item.metric_code}</div><div className="mt-1 font-mono text-sm text-gray-200">{item.metric_value??'—'} <span className="text-[10px] text-gray-600">{item.unit}</span></div></div>)}</div></section><section className="rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">复盘结论</h2><span className={`rounded border px-2 py-0.5 text-[10px] ${view.status==='sealed'?'border-emerald-500/25 text-emerald-300':'border-amber-500/25 text-amber-200'}`}>{view.status}</span></div><label className="block text-[11px] text-gray-500">当日总结<textarea disabled={view.status==='sealed'||role!=='admin'} value={summary} onChange={event=>setSummary(event.target.value)} className="mt-1 min-h-28 w-full rounded border border-crypto-border bg-crypto-bg p-3 text-xs text-gray-200 disabled:opacity-70" /></label><label className="mt-3 block text-[11px] text-gray-500">次日计划<textarea disabled={view.status==='sealed'||role!=='admin'} value={plan} onChange={event=>setPlan(event.target.value)} className="mt-1 min-h-28 w-full rounded border border-crypto-border bg-crypto-bg p-3 text-xs text-gray-200 disabled:opacity-70" /></label>{role==='admin'&&view.status!=='sealed'&&<div className="mt-3 flex gap-2"><button type="button" onClick={()=>void save()} disabled={saving} className="inline-flex items-center gap-1 rounded bg-blue-600 px-3 py-2 text-xs"><Save className="h-3 w-3" />保存</button><button type="button" onClick={()=>void seal()} disabled={saving} className="inline-flex items-center gap-1 rounded border border-emerald-500/30 px-3 py-2 text-xs text-emerald-200"><ShieldCheck className="h-3 w-3" />封存</button></div>}</section></div>
      <section className="mt-4 rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-sm font-semibold">证据时间线</h2><p className="mt-1 text-[10px] text-gray-600">所有对象保留 source route / ID / evidence hash</p></div><div className="flex max-w-full overflow-x-auto">{categories.map(item=><button key={item} onClick={()=>setCategory(item)} className={`shrink-0 rounded px-2.5 py-1.5 text-[11px] ${category===item?'bg-blue-500/15 text-blue-200':'text-gray-500'}`}>{labels[item]} {item==='all'?view.items.length:view.counts[item]||0}</button>)}</div></div><div className="space-y-2">{visible.map(item=><div key={String(item.id||item.item_key)} className="grid gap-2 rounded border border-crypto-border bg-crypto-bg/50 p-3 text-xs md:grid-cols-[150px_90px_1fr_260px]"><span className="text-gray-500">{dt(item.occurred_at)}</span><span className="text-blue-200">{labels[item.category]||item.category}</span><div><div className="text-gray-200">{item.title}</div><div className="mt-1 text-[10px] text-gray-600">{item.summary||'—'}</div></div><span className="truncate font-mono text-[10px] text-gray-700">{item.source_object_type}:{item.source_object_id}</span></div>)}</div></section></>}
    <div className="mt-4 flex items-center gap-2 text-[10px] text-gray-700"><Clock3 className="h-3 w-3" />GET 只读取已存复盘；当前读取 writes_performed={String(view?.writes_performed??false)}</div>
  </div>
}
