import { useEffect, useState } from 'react'
import { Activity, AlertTriangle, BarChart3, BellRing, BookOpenCheck, Eye, RefreshCw, Ruler, ShieldCheck } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { operationsCurrentApi } from '../api/client'
import { useAuth } from '../auth/AuthProvider'
import type { WatchContext, WatchRule } from '../types/operations'


const tabs = ['策略信号', '订单与成交', '图表联动', '规则', '告警'] as const
type Tab = typeof tabs[number]
const dt = (value: unknown) => value ? String(value).replace('T', ' ').slice(0, 19) : '—'

export default function Watch() {
  const { role } = useAuth(); const [tab, setTab] = useState<Tab>('策略信号'); const [context, setContext] = useState<WatchContext | null>(null); const [rules, setRules] = useState<WatchRule[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  const load = async () => { setLoading(true); try { const [nextContext, nextRules] = await Promise.all([operationsCurrentApi.context('audit'), operationsCurrentApi.rules('audit')]); setContext(nextContext); setRules(nextRules.items); setMessage('') } catch (error: any) { setMessage(error?.response?.data?.detail || error?.message || '盯盘证据读取失败') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const preview = async (rule: WatchRule) => { const result = await operationsCurrentApi.previewRule(rule.id); setMessage(`预览完成：扫描 ${result.source_count || 0}，命中 ${result.matched || 0}；零写入`) }
  const evaluate = async (rule: WatchRule) => { if (!window.confirm(`确认评估「${rule.name}」？只生成告警，不下单、不改 Paper。`)) return; const result = await operationsCurrentApi.evaluateRule(rule.id); setMessage(`评估完成：新增 ${result.alerts_created || 0} 条告警，订单 ${result.orders_created || 0}`); await load() }
  const data = context
  const summary: Array<[string, string | number, LucideIcon]> = [['Paper 实例',data?.instances.length ?? '—',Activity],['策略信号',data?.signals.length ?? '—',Eye],['订单 / 成交',data ? `${data.orders.length} / ${data.trades.length}` : '—',BookOpenCheck],['活动告警',data?.alerts.filter((item) => item.status==='active').length ?? '—',BellRing]]
  return <div className="h-full overflow-y-auto bg-crypto-bg px-4 py-4 text-gray-100 sm:px-6"><header className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg border border-blue-500/25 bg-blue-500/10"><Eye className="h-5 w-5 text-blue-300" /></div><div><div className="text-[10px] font-semibold uppercase tracking-[.18em] text-blue-300/80">Evidence Watch</div><h1 className="text-xl font-bold">盯盘</h1></div></div><button type="button" onClick={() => void load()} className="inline-flex items-center gap-1.5 rounded border border-crypto-border px-3 py-2 text-xs text-gray-400"><RefreshCw className={`h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} />刷新</button></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summary.map(([label,value,Icon]) => <div key={label} className="rounded-xl border border-crypto-border bg-crypto-card p-4"><div className="flex items-center justify-between text-[11px] text-gray-500"><span>{label}</span><Icon className="h-4 w-4 text-blue-400/70" /></div><div className="mt-2 font-mono text-2xl font-semibold">{value}</div></div>)}</div>
    <section className="mt-4 rounded-xl border border-crypto-border bg-crypto-card"><div role="tablist" className="flex overflow-x-auto border-b border-crypto-border p-2">{tabs.map((item) => <button role="tab" aria-selected={tab===item} key={item} onClick={() => setTab(item)} className={`shrink-0 rounded px-3 py-2 text-xs ${tab===item?'bg-blue-500/15 text-blue-200':'text-gray-500'}`}>{item}</button>)}</div>{message && <div className="m-3 rounded border border-blue-500/20 bg-blue-500/[.06] px-3 py-2 text-xs text-blue-100">{message}</div>}<div className="p-4">
      {tab==='策略信号' && (data?.signals.length ? <div className="space-y-2">{data.signals.slice(0,30).map((item) => <div key={item.id} className="grid gap-2 rounded border border-crypto-border bg-crypto-bg/50 p-3 text-xs md:grid-cols-[110px_110px_1fr_160px]"><span className="font-mono text-gray-300">{item.symbol}</span><span className="text-blue-200">{item.signal_type}</span><span className="truncate font-mono text-gray-600">{item.paper_instance_id}</span><span className="text-gray-500">{dt(item.signal_time)}</span></div>)}</div>:<div className="text-xs text-gray-500">暂无策略信号</div>)}
      {tab==='订单与成交' && <div className="grid gap-4 xl:grid-cols-2"><EvidenceList title="订单" items={data?.orders || []} /><EvidenceList title="成交" items={data?.trades || []} /></div>}
      {tab==='图表联动' && <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-lg border border-crypto-border bg-crypto-bg/50 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><BarChart3 className="h-4 w-4 text-blue-300" />证券证据联动</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{Object.entries(data?.symbol_names || {}).slice(0,12).map(([symbol,name]) => <div key={symbol} className="rounded border border-crypto-border p-3"><div className="text-xs">{name || '证券'}</div><div className="mt-1 font-mono text-[10px] text-gray-600">{symbol}</div></div>)}</div></div><div className="rounded-lg border border-crypto-border bg-crypto-bg/50 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><ShieldCheck className="h-4 w-4 text-blue-300" />观察边界</div><p className="mt-3 text-xs leading-5 text-gray-500">图表只联动信号、订单、成交和风险证据；不提供交易执行。</p></div></div>}
      {tab==='规则' && <div className="space-y-2">{rules.map((rule) => <div key={rule.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-crypto-border bg-crypto-bg/50 p-3"><div><div className="text-xs font-semibold">{rule.name}</div><div className="mt-1 text-[10px] text-gray-600">{rule.rule_type} · v{rule.rule_version} · {rule.severity}</div></div><div className="flex gap-2"><button type="button" onClick={() => void preview(rule)} className="inline-flex items-center gap-1 rounded border border-crypto-border px-2 py-1.5 text-[11px] text-gray-300"><Ruler className="h-3 w-3" />预览</button>{role==='admin' && <button type="button" onClick={() => void evaluate(rule)} className="inline-flex items-center gap-1 rounded border border-amber-500/30 px-2 py-1.5 text-[11px] text-amber-200"><AlertTriangle className="h-3 w-3" />评估告警</button>}</div></div>)}{rules.length===0&&<div className="text-xs text-gray-500">暂无规则</div>}</div>}
      {tab==='告警' && <div className="space-y-2">{(data?.alerts||[]).map((item) => <div key={item.id} className="rounded border border-crypto-border bg-crypto-bg/50 p-3"><div className="flex justify-between gap-2"><span className="text-xs font-semibold">{item.title}</span><span className="text-[10px] text-gray-600">{item.severity} · {item.status}</span></div><div className="mt-1 text-xs text-gray-500">{item.message}</div><div className="mt-1 font-mono text-[10px] text-gray-700">{item.paper_instance_id || '系统级'} · {dt(item.triggered_at)}</div></div>)}</div>}
    </div></section></div>
}

function EvidenceList({title,items}:{title:string;items:Array<Record<string,any>>}) { return <div><div className="mb-2 text-xs font-semibold">{title} <span className="font-mono text-gray-600">{items.length}</span></div><div className="max-h-96 space-y-2 overflow-y-auto">{items.slice(0,30).map((item) => <div key={String(item.id)} className="rounded border border-crypto-border bg-crypto-bg/50 p-3 text-xs"><div className="flex justify-between gap-2"><span className="font-mono">{item.symbol || item.code || '—'}</span><span className="text-gray-500">{item.status || item.side || '—'}</span></div><div className="mt-1 truncate font-mono text-[10px] text-gray-700">{item.paper_instance_id}</div></div>)}</div></div> }
